### ISSUE TITLE
publish 'push' branch

### ISSUE THREAD

**Issue by leviwheatcroft** [superwolff/metalsmith-cloudinary#7]
Hey, I'd like to publish 'push' branch. It's been ready to ship for quite a while.

I've been using it myself, seems relatively stable.

I can sort it out if you'd like to give me colaborator rights on npm.

**Comment by ismay** [comment]
Ah yes of course. I've added you as an owner on npm 👍  Thanks for the help with this package!

**Comment by ismay** [comment]
Also added you to the org btw.
